loading training instances, dir instances/randomip_n60_m60 idx 0
loading training instances, dir instances/randomip_n60_m60 idx 1
loading training instances, dir instances/randomip_n60_m60 idx 2
loading training instances, dir instances/randomip_n60_m60 idx 3
loading training instances, dir instances/randomip_n60_m60 idx 4
loading training instances, dir instances/randomip_n60_m60 idx 5
loading training instances, dir instances/randomip_n60_m60 idx 6
loading training instances, dir instances/randomip_n60_m60 idx 7
loading training instances, dir instances/randomip_n60_m60 idx 8
loading training instances, dir instances/randomip_n60_m60 idx 9
loading training instances, dir instances/randomip_n60_m60 idx 10
loading training instances, dir instances/randomip_n60_m60 idx 11
loading training instances, dir instances/randomip_n60_m60 idx 12
loading training instances, dir instances/randomip_n60_m60 idx 13
loading training instances, dir instances/randomip_n60_m60 idx 14
loading training instances, dir instances/randomip_n60_m60 idx 15
loading training instances, dir instances/randomip_n60_m60 idx 16
loading training instances, dir instances/randomip_n60_m60 idx 17
loading training instances, dir instances/randomip_n60_m60 idx 18
loading training instances, dir instances/randomip_n60_m60 idx 19
Traceback (most recent call last):
  File "rl_cuts.py", line 212, in <module>
    actor = torch.load(PATH)
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/Users/zhangqiming/opt/anaconda3/envs/LtC/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /Users/distiller/project/conda/conda-bld/pytorch_1579022061893/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /Users/distiller/project/conda/conda-bld/pytorch_1579022061893/work/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x109b3b267 in libc10.dylib)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 2350 (0x1240ba50e in libtorch.dylib)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 143 (0x1240b9b5f in libtorch.dylib)
frame #3: void pybind11::cpp_function::initialize<void pybind11::detail::initimpl::constructor<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::execute<pybind11::class_<caffe2::serialize::PyTorchStreamReader>, 0>(pybind11::class_<caffe2::serialize::PyTorchStreamReader>&)::'lambda'(pybind11::detail::value_and_holder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >), void, pybind11::detail::value_and_holder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor>(pybind11::class_<caffe2::serialize::PyTorchStreamReader>&&, void (*)(pybind11::detail::value_and_holder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, pybind11::detail::is_new_style_constructor const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 147 (0x11ba20413 in libtorch_python.dylib)
frame #4: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3372 (0x11b41a1fc in libtorch_python.dylib)
frame #5: _PyMethodDef_RawFastCallDict + 541 (0x102a4b19d in python3.7)
frame #6: _PyObject_FastCallDict + 104 (0x102a4a3f8 in python3.7)
frame #7: method_call + 122 (0x102a4ed7a in python3.7)
frame #8: PyObject_Call + 127 (0x102a4cb1f in python3.7)
frame #9: slot_tp_init + 407 (0x102acd387 in python3.7)
frame #10: type_call + 246 (0x102ad4976 in python3.7)
frame #11: _PyObject_FastCallKeywords + 175 (0x102a4bcdf in python3.7)
frame #12: call_function + 455 (0x102b84907 in python3.7)
frame #13: _PyEval_EvalFrameDefault + 20180 (0x102b7c344 in python3.7)
frame #14: _PyEval_EvalCodeWithName + 532 (0x102b75c44 in python3.7)
frame #15: _PyFunction_FastCallDict + 444 (0x102a4a79c in python3.7)
frame #16: slot_tp_init + 181 (0x102acd2a5 in python3.7)
frame #17: type_call + 246 (0x102ad4976 in python3.7)
frame #18: _PyObject_FastCallKeywords + 175 (0x102a4bcdf in python3.7)
frame #19: call_function + 455 (0x102b84907 in python3.7)
frame #20: _PyEval_EvalFrameDefault + 22144 (0x102b7caf0 in python3.7)
frame #21: _PyEval_EvalCodeWithName + 532 (0x102b75c44 in python3.7)
frame #22: _PyFunction_FastCallKeywords + 395 (0x102a4c28b in python3.7)
frame #23: call_function + 183 (0x102b847f7 in python3.7)
frame #24: _PyEval_EvalFrameDefault + 20180 (0x102b7c344 in python3.7)
frame #25: _PyEval_EvalCodeWithName + 532 (0x102b75c44 in python3.7)
frame #26: PyRun_FileExFlags + 235 (0x102be18bb in python3.7)
frame #27: PyRun_SimpleFileExFlags + 502 (0x102be1286 in python3.7)
frame #28: pymain_run_file + 160 (0x102c0dc70 in python3.7)
frame #29: pymain_run_filename + 123 (0x102c0d56b in python3.7)
frame #30: pymain_run_python + 145 (0x102c0cd51 in python3.7)
frame #31: pymain_main + 27 (0x102c0c9cb in python3.7)
frame #32: main + 89 (0x102a21519 in python3.7)
frame #33: start + 462 (0x10aeb951e in dyld)